### ISSUE TITLE
other coliforms

### ISSUE THREAD

**Issue by rachelaronoff** [hammerdirt/water-quality-2016-2017#1]
in the new improved 'figure 7' for the 'case study' it should say 'other coliforms' not 'non-fecal' ones, please.  hasta luego!

**Comment by rachelaronoff** [comment]
(2017 complete species grid)

**Comment by hammerdirt** [comment]
This is taken care of, the 2016 barchart was also changed for the med-blue output.

Let me know when if its good so the issue can be closed.

**Comment by hammerdirt** [comment]
This is resolved
