### ISSUE TITLE
rain issues

### ISSUE THREAD

**Issue by rachelaronoff** [hammerdirt/water-quality-2016-2017#3]
Dear Roger,
There are too many rain files and it seems like 2017 is wrong.
Here - water-quality-2016-2017/data/CSV/rain2017.csv - the numbers have decimals (units?).
Here - water-quality-2016-2017/data/rainfall.csv - numbers are in inches and dates are 2018.
 (but I think the rainfall2016.csv file there looks ok.)
Here - water-quality-2016-2017/data/JSON/rain2017.json - the numbers have decimals (units?).(might be like the csv at top) seems wrong.
Here - water-quality-2016-2017/data/JSON/rain_2017.json - it seems to be the same problem...
Nothing seems to match the mm number that are available here: https://www.historique-meteo.net/europe/suisse/montreux/2017/06/#jour . which I tried to make as a .csv file and mailed you today...
Thanks for all your help.  would love to have output that matchs this (as the other graphs we had made), but that seems correct for the 2017 data...
![Fig4AB](https://user-images.githubusercontent.com/48484650/73004824-3fd7f700-3e08-11ea-9cbc-6300ca48a205.png)

**Comment by hammerdirt** [comment]
The error was traced to a document (word document) that had the rainfall values embedded in a table. Just not a good way to share data.

The .csv file you sent works fine and the rainfall 2017 data has been replaced.

The charts are available at /data/charts

At your service

Roger at hammerdirt

**Comment by rachelaronoff** [comment]
thank you!
will also double check more and am glad the deadline was extended!
when can we meet in person?  maybe closer to you? (Anna is also in the area
now)
:)

**Comment by rachelaronoff** [comment]
still think we should have both 2016 and 2017 data all from the same source (i.e. link below)
and clean up the repo so we don't have all the different rain files still possibly confusing things.  
thx!!

https://www.historique-meteo.net/europe/suisse/montreux/2017/06/#jour
--

**Comment by hammerdirt** [comment]
Rachel the "new" rain data for 2016 is included
